### ISSUE TITLE
Error when running npm run dev

### ISSUE THREAD

**Issue by Michael-Reich** [scottbedard/oc-vuetober-theme#16]
When I run the command npm run dev I get this Error:

```
> oc-vuetober-theme@2.1.0 dev /home/forge/mywebsite.com/themes/mytheme
> node build/dev-server.js

internal/net.js:17
    throw new RangeError('"port" argument must be >= 0 and < 65536');
    ^

RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1390:5)
    at EventEmitter.listen (/home/forge/mywebsite.com/themes/mytheme/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/forge/mywebsite.com/themes/mytheme/build/dev-server.js:103:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! oc-vuetober-theme@2.1.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oc-vuetober-theme@2.1.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oc-vuetober-theme package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oc-vuetober-theme
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oc-vuetober-theme
```

**Comment by scottbedard** [comment]
Hmm, that's a new one. I would recommend trying to manually set [this value](https://github.com/scottbedard/oc-vuetober-theme/blob/master/build/dev-server.js#L19) to `8080` or something. If that doesn't work, could you provide some information about what kind of machine you're using?

**Comment by Michael-Reich** [comment]
When I change the value it opens but he opens http://localhost:3000 and when I open http://localhost:8080 he displays `Cannot GET /`

**Comment by scottbedard** [comment]
That is actually what is expected. The serving of the initial page is a bit unusual because we want to send the first request to October, and then inject our development assets into it. You should be seeing `localhost:3000` when you fire up the dev server, regardless of what you set that variable to.

If you need to change from something other than port `3000`, you'll need to [configure browsersync](https://browsersync.io/docs/options#option-port) with your desired port.

**Comment by Michael-Reich** [comment]
Worked after I did change the value manually to `8080`.

What could caused the problem?
