### ISSUE TITLE
yarn run dev throws error.

### ISSUE THREAD

**Issue by CptMeatball** [scottbedard/oc-vuetober-theme#22]
`yarn run dev` throws following error. Any idea what's going wrong?

I'm new to the entire `node` and `vue` scene, so this might be a nooby question though haha.

```
internal/net.js:17
    throw new RangeError('"port" argument must be >= 0 and < 65536');
    ^

RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1389:5)
    at EventEmitter.listen (/Users/antoniehogewoning/Web/Sites/rebel59-2017/themes/rebel59/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/antoniehogewoning/Web/Sites/rebel59-2017/themes/rebel59/build/dev-server.js:103:22)
    at Module._compile (module.js:570:32)
```

**Comment by scottbedard** [comment]
Looks like you might be running into the same issue [discussed here](https://github.com/scottbedard/oc-vuetober-theme/issues/16). Take a look at that solution, and let me know if you still have a problem.

**Comment by CptMeatball** [comment]
Ah, darn. Hadn't looked their. Although you say: 

> That is expected behavior. The serving of the initial page is a bit unusual because we need to send the first request to October, and then inject our development assets into it. You should be seeing localhost:3000 when you fire up the dev server, regardless of what you set that variable to.

How do I get it to show my app? (building and everything works fine tho!)

**Comment by scottbedard** [comment]
Is the dev server starting up? If so, go ahead and hit http://localhost:3000 in the browser and you should be good to go.

**Comment by CptMeatball** [comment]
Both the laravel dev server `artisan serve`, and the webpack dev server `yarn run dev` are starting up.  It seems really inconsistent, as the previous days it worked flawlessly, but now I keep getting the `cannot get /` error. 

I followed the steps that you've linked but someway or another it doesn't work.

Steps:

1. `pa serve` in October Root
2. `yarn run dev` in theme root.
3.  `cannot get /` error.

**Comment by scottbedard** [comment]
I haven't tried using it with `artisan serve` before, but I suspect it is because [this piece of your config](https://github.com/scottbedard/oc-vuetober-theme/blob/master/build/dev-server.js#L75) is not pointing to the correct url. The vuetober dev setup is a bit tricky, it first sends a request to this url, and then injects your development assets into it. Try changing that value to match whatever url artisan is serving your app on.

**Comment by scottbedard** [comment]
Closing due to inactivity
