### ISSUE TITLE
Failed to decode param.

### ISSUE THREAD

**Issue by jakubkoje** [scottbedard/oc-vuetober-theme#54]
I tried to install a vuetober theme but after vue add vuetober i cant run serve. This is the error I get in console when connecting to site. 

Vue server without vuetober works.
Thanks

`URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/layer.js:172:12)           at Layer.match (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/layer.js:123:27)            at matchLayer (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/index.js:574:18)
    at next (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/middleware/init.js:40:5)           at Layer.handle [as handle_request] (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/index.js:317:13)            at /mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/index.js:335:12)
    at next (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/index.js:275:10)
    at query (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/index.js:317:13)            at /mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/mnt/c/laragon/www/vuetober/themes/mytheme/node_modules/express/lib/router/index.js:335:12)`

**Comment by scottbedard** [comment]
Hmm it's hard to say without looking at the theme. Could you upload it to github so we can take a look?

**Comment by jakubkoje** [comment]
It was likely my mistake. I was trying to acess the hotreload server from localhost when I set the link to my apache server. If I try to acess it through the set domain and it works. Is it intended?

**Comment by scottbedard** [comment]
Yup, only development assets are served via webpack dev server. The catch-all `.htm` file is written to disk and your main entry point will remain the same 👍
